project:
  type: website

website:
  title: "Jayani Lakshika"
  page-footer:
    background: "#4292c6"
    right: "© 2021-2024, Jayani P.G. Lakshika"
  navbar:
    background: "#69A1D6"
    left:
      - href: index.qmd
        text: Home
      - href: cv/index.qmd
        text: CV
      - href: software.qmd
        text: Software
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: talks.qmd
        text: Talks
      - href: visiting.qmd
        text: Visiting
      - href: teaching.qmd
        text: Teaching
      - href: Blogs.qmd
        text: Blog
      - href: Materials.qmd
        text: Materials

format:
  html:
    theme:
      light: lumen
      dark: [lumen, theme-dark.scss]
    css: styles.css
    toc: true
    backgroundcolor: "#deebf7"
editor: visual

